version: '2'
services:
  secu_manif:
    container_name: secu-manif
    build:
      context: .
      dockerfile: Dockerfile
    #ports:
    #  - '3713:80'
    restart: always
    networks:
      - npm-network

networks:
  npm-network:
    external: true
